import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import ArrowLeftIcon from "@/app/_icon/arrow-left";
import image1 from "../../public/images/website.png";

export default function Porto() {
  return (
    <>
      <Head>
        <title>Porto - As&apos;ad Personal Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto w-screen p-6">
        <nav className="flex">
          <Link
            href="/"
            className="my-4 px-4 py-2 transition flex items-center gap-2 rounded border-2 active:scale-95 bg-transparent border-stone-400 hover:bg-stone-200 dark:text-white dark:border-stone-200 dark:hover:bg-stone-100 dark:hover:text-black"
          >
            <ArrowLeftIcon />
            To Home
          </Link>
        </nav>

        <section className="max-w-3xl mx-auto">
          <h1 className="text-3xl dark:text-white">Portfolio</h1>
          <h4 className="text-xl dark:text-slate-500">
            My work & hobby projects are listed here
          </h4>

          <h5 className="mt-10 text-xl dark:text-white">
            Selected Work Projects
          </h5>
          <div className="mt-2 grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Lumbung Dana */}
            <Card
              title="Lumbung Dana web app"
              desc="Aplikasi web untuk mengelola dana pinjaman peer-to-peer"
              imageUrl="/images/lumbung_dana.png"
              links={{
                app: "https://lumbungdana.co.id/",
              }}
            />

            {/* Moodah */}
            {/* <Card
              title="Moodah mobile app"
              desc="Aplikasi Android & iOS untuk mengelola ERP perusahaan yang terhubung ke sistem Moodah"
              links={{}}
            /> */}

            {/* Transfez */}
            {/* <Card
              title="Transfez mobile app"
              desc="Aplikasi Android & iOS untuk mengirim uang ke luar negeri"
              links={{
                app: "https://play.google.com/store/apps/details?id=com.indokoala.transfez&hl=id&gl=US",
              }}
            /> */}

            {/* IDF */}
            <Card
              title="Yayasan IDF site"
              desc="Website untuk mengenalkan Yayasan IDF kepada masyarakat"
              imageUrl="/images/idf.png"
              links={{ app: "https://infradigitalfoundation.netlify.app/" }}
            />

            {/* Iyada */}
            <Card
              title="PT Iyada company profile site"
              desc="Website untuk mengenalkan PT Iyada kepada masyarakat"
              imageUrl="/images/iyada.png"
              links={{ app: "https://iyada.id/" }}
            />

            {/* Pelajar */}
            <Card
              title="Pelajar mobile app"
              desc="Aplikasi mobile untuk wali murid mengelola seluruh keperluan digital siswa"
              imageUrl="/images/pelajar.png"
              links={{
                app: "https://play.google.com/store/apps/details?id=io.infradigital.app.pelajar&hl=en_US",
              }}
            />

            {/* Pordi */}
            <Card
              title="Portal Digital web app"
              desc="Aplikasi web untuk staf sekolah mengelola seluruh keperluan digital sekolahnya"
              imageUrl="/images/pordi.png"
              links={{
                app: "https://pordi.infradigital.io/",
              }}
            />

            {/* Pager */}
            <Card
              title="Pager web app"
              desc="Aplikasi web SaaS untuk mengelola notifikasi aplikasi web3"
              imageUrl="/images/pager.png"
              links={{
                app: "https://app.getpager.xyz/onboarding",
              }}
            />
          </div>

          <h5 className="mt-10 text-xl dark:text-white">Hobby Projects</h5>
          <div className="mt-2 grid grid-cols-1 md:grid-cols-2 gap-4 ">
            {/* GlobalTimeDetector */}
            <Card
              title="Global Time Detector"
              desc="A simple app to detect a random time and convert it to your timezone"
              imageUrl="/images/global-time-detector.png"
              links={{
                app: "https://globaltimedetector.vercel.app/",
                github: "https://github.com/AsadSaleh/detect-time",
              }}
            />

            {/* TimeToSync */}
            <Card
              title="TimeToSync"
              desc="A beatiful clock app for team sync across the globe"
              imageUrl="/images/timetosync.png"
              links={{
                app: "https://timetosync.netlify.app/",
                github: "https://github.com/AsadSaleh/time-ui",
              }}
            />

            {/* Pajakin */}
            <Card
              title="Pajakin"
              desc="Free tax calculator for Indonesian worker (Pph 21)"
              imageUrl="/images/pajakin.png"
              links={{
                app: "https://pajakin.vercel.app/",
                github: "https://github.com/AsadSaleh/pajakin",
              }}
            />

            {/* Is it Retina? */}
            <Card
              title="Is it Retina?"
              desc="Apakah layar kamu 'Retina Display'?"
              imageUrl="/images/isitretina.png"
              links={{
                app: "https://is-it-retina.vercel.app/",
                github: "https://github.com/AsadSaleh/is_it_retina",
              }}
            />

            {/* React native */}
            <Card
              title="Flip mobile app (ui only)"
              desc="A sample React Native app which follows Flip's delightful UI"
              imageUrl=""
              links={{
                github: "https://github.com/AsadSaleh/flip_react_native_app",
              }}
            />

            {/* Drop em */}
            <Card
              title="Drop Em"
              desc="Component example for creating Drag & Drop file in React"
              links={{ github: "https://github.com/AsadSaleh/drop-em" }}
              imageUrl=""
            />

            {/* This website */}
            <Card
              title="This website"
              desc=""
              imageUrl="/images/website.png"
              links={{
                github: "https://github.com/AsadSaleh/web-asad",
              }}
            />
          </div>
        </section>
      </main>
    </>
  );
}

function Card(props: {
  imageUrl?: string;
  desc: string;
  title: string;
  links: { app?: string; github?: string };
}) {
  return (
    <div className="p-2 md:p-6 flex flex-col justify-between gap-2 rounded-xl border border-stone-200 dark:border-stone-700 bg-white dark:bg-slate-900">
      <div>
        {/* Image */}
        <div className="h-[200px] flex items-center justify-center">
          {props.imageUrl ? (
            <Image
              src={props.imageUrl}
              alt={props.title}
              width={400}
              height={200}
            />
          ) : (
            <div className="flex h-[180px] w-full items-center text-sm justify-center bg-slate-800 rounded-md">
              <p className="font-light text-center text-slate-400">No Image</p>
            </div>
          )}
        </div>

        {/* Title & Desc */}
        <div className="mt-2">
          <p className="text-xl tracking-wide font-semibold dark:text-white">
            {props.title}
          </p>
          <p className="text-md text-stone-600 dark:text-stone-400">
            {props.desc}
          </p>
        </div>
      </div>

      {/* Link */}
      <div className="mt-2 flex justify-start items-start gap-2">
        {Object.entries(props.links).map(([type, url]) => {
          if (type === "github") {
            return (
              <a
                key={type}
                href={url}
                target="_blank"
                rel="noopener noreferrer"
                className="font-mono text-xs py-2 px-3 rounded-xl transition active:scale-90 text-slate-800 bg-stone-200 hover:bg-stone-300 dark:bg-slate-700 dark:text-white dark:hover:bg-slate-600"
              >
                GitHub
              </a>
            );
          }
          return (
            <a
              key={type}
              href={url}
              target="_blank"
              rel="noopener noreferrer"
              className="font-mono text-xs py-2 px-3 rounded-xl transition active:scale-90 text-slate-800 bg-stone-200 hover:bg-stone-300 dark:bg-slate-700 dark:text-white dark:hover:bg-slate-600"
            >
              Open App
            </a>
          );
        })}
      </div>
    </div>
  );
}
