import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>As&apos;ad Personal Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="flex gap-4">
          <a
            href="https://github.com/AsadSaleh"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.description}
          >
            <p>Github</p>
          </a>
          <a
            href="https://www.linkedin.com/in/as-ad-saleh-umar-876608a4/"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.description}
          >
            <p>LinkedIn</p>
          </a>
          <a
            href="https://stackoverflow.com/users/9844546/asad-s"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.description}
          >
            <p>StackOverflow</p>
          </a>
        </div>

        <div className={"" + styles.center}>
          <div className="flex gap-4 items-center">
            <Image
              src="/images/profile.jpg"
              width={80}
              height={80}
              alt="As'ad"
              className="rounded-full"
            />
            <div>
              <p className="text-xl text-stone-400 italic">
                Hello there! <br />
              </p>
              <p className="text-3xl">
                <span className="text-orange-300">[</span>As&apos;ad
                <span className="text-orange-300">]</span>&apos;s &nbsp;here, a
                software
                <br /> developer from Indonesia.
              </p>
            </div>
            <p></p>
          </div>
        </div>

        <div className={styles.grid}>
          <Link href="/porto" className={styles.card}>
            <h2 className={inter.className}>
              Portfolio <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Let&apos;s see As&apos;ad&apos;s playing cards
            </p>
          </Link>

          <Link href="/about" className={styles.card}>
            <h2 className={inter.className}>
              About <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Read a boring stroy about my journey
            </p>
          </Link>

          <a
            href="https://asadghanim.notion.site/Programming-Curriculum-60b88f5ac71f44599f1b537d62173b12"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Blogs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover what&apos;s inside my head
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
