/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortoIndexRouteImport } from './routes/porto/index'
import { Route as PajakinIndexRouteImport } from './routes/pajakin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as AppRetinaIndexRouteImport } from './routes/app/retina/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortoIndexRoute = PortoIndexRouteImport.update({
  id: '/porto/',
  path: '/porto/',
  getParentRoute: () => rootRouteImport,
} as any)
const PajakinIndexRoute = PajakinIndexRouteImport.update({
  id: '/pajakin/',
  path: '/pajakin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRetinaIndexRoute = AppRetinaIndexRouteImport.update({
  id: '/app/retina/',
  path: '/app/retina/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/about': typeof AboutIndexRoute
  '/pajakin': typeof PajakinIndexRoute
  '/porto': typeof PortoIndexRoute
  '/app/retina': typeof AppRetinaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/about': typeof AboutIndexRoute
  '/pajakin': typeof PajakinIndexRoute
  '/porto': typeof PortoIndexRoute
  '/app/retina': typeof AppRetinaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/about/': typeof AboutIndexRoute
  '/pajakin/': typeof PajakinIndexRoute
  '/porto/': typeof PortoIndexRoute
  '/app/retina/': typeof AppRetinaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/tanstack-query'
    | '/about'
    | '/pajakin'
    | '/porto'
    | '/app/retina'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/tanstack-query'
    | '/about'
    | '/pajakin'
    | '/porto'
    | '/app/retina'
  id:
    | '__root__'
    | '/'
    | '/demo/tanstack-query'
    | '/about/'
    | '/pajakin/'
    | '/porto/'
    | '/app/retina/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  AboutIndexRoute: typeof AboutIndexRoute
  PajakinIndexRoute: typeof PajakinIndexRoute
  PortoIndexRoute: typeof PortoIndexRoute
  AppRetinaIndexRoute: typeof AppRetinaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/porto/': {
      id: '/porto/'
      path: '/porto'
      fullPath: '/porto'
      preLoaderRoute: typeof PortoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pajakin/': {
      id: '/pajakin/'
      path: '/pajakin'
      fullPath: '/pajakin'
      preLoaderRoute: typeof PajakinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/retina/': {
      id: '/app/retina/'
      path: '/app/retina'
      fullPath: '/app/retina'
      preLoaderRoute: typeof AppRetinaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  AboutIndexRoute: AboutIndexRoute,
  PajakinIndexRoute: PajakinIndexRoute,
  PortoIndexRoute: PortoIndexRoute,
  AppRetinaIndexRoute: AppRetinaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
